# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv001-iot
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   nfs:
#     server: 192.168.0.103
#     path: "/tmp/data/"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001-iot
spec:
  capacity:-
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv001
  persistentVolumeReclaimPolicy: Recycle
